// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfS4MYkFIM9NTQxM5YizPOc-zhLf7JJXw',
    appId: '1:464928025141:web:4ba068f53ff227a5b3df7c',
    messagingSenderId: '464928025141',
    projectId: 'fooddelivery-f1b9b',
    authDomain: 'fooddelivery-f1b9b.firebaseapp.com',
    storageBucket: 'fooddelivery-f1b9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEvPEvjSH3wdhJ6j_DzvoKRgeSep-ahmc',
    appId: '1:464928025141:android:db6d33fcff6f8065b3df7c',
    messagingSenderId: '464928025141',
    projectId: 'fooddelivery-f1b9b',
    storageBucket: 'fooddelivery-f1b9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR9M9BxNXI-2FVuCKN8UX0AgFhMRYdR6g',
    appId: '1:464928025141:ios:f5c6fb50fbb2e7b9b3df7c',
    messagingSenderId: '464928025141',
    projectId: 'fooddelivery-f1b9b',
    storageBucket: 'fooddelivery-f1b9b.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR9M9BxNXI-2FVuCKN8UX0AgFhMRYdR6g',
    appId: '1:464928025141:ios:f5c6fb50fbb2e7b9b3df7c',
    messagingSenderId: '464928025141',
    projectId: 'fooddelivery-f1b9b',
    storageBucket: 'fooddelivery-f1b9b.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfS4MYkFIM9NTQxM5YizPOc-zhLf7JJXw',
    appId: '1:464928025141:web:2d429b2e4796b73ab3df7c',
    messagingSenderId: '464928025141',
    projectId: 'fooddelivery-f1b9b',
    authDomain: 'fooddelivery-f1b9b.firebaseapp.com',
    storageBucket: 'fooddelivery-f1b9b.appspot.com',
  );
}
